os:
  - "linux"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - cmake
env: COMPILER=g++-9
install:
  make cmake

language:
  - "c++"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make