os:
  - "linux"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install make xorg xorg-dev libc6-dev libvulkan1 libvulkan-dev vulkan-utils libxcursor1 libx11-dev
  - git clone https://github.com/KhronosGroup/Vulkan-Headers
  - sudo cp -r Vulkan-Headers/include/vulkan /usr/include

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
env: COMPILER=g++-9

language:
  - "c++"

script:
  - git clone https://github.com/premake/premake-core
  - cd premake-core
  - make -f Bootstrap.mak linux
  - cd bin/release/
  - sudo cp *.so /usr/lib/
  - sudo cp premake5 /usr/bin
  - cd ~
  - git clone --recursive https://github.com/inugami-dev64/deng
  - cd deng
  - premake5 --sandbox-mode=all gmake
  - make config=debug_linux
