import: 
  windows: 
    - modules/freetype2/build.yml
premake:
  cc: gcc
  cxx: g++
  cc_flags: 
    - Wall
    - m64
    - O3
  cxx_flags: 
    - Wall
    - m64 
    - std=c++11
    - O3
  include_path:
    - "headers"
    linux:
      - "/usr/include/freetype2"
      - "/usr/include/freetype2/include"
    windows:
      - "modules/freetype2/include"
      - "modules/freetype2/include/freetype"
      - "C:/VulkanSDK/[VERSION]"
  src_dir: src/
  build_dir: build/
  project_name: deng

tasks: 
  dam:
    type: exec
    src:
      - das/dam.c
      - das/das_handler.c
      - das/data_loader.c
      - common/hashmap.c
      - common/common.c
  
  libdeng:
    type: dynamic_lib
    src: 
      # deng main sources
      - deng/camera.cpp
      - deng/deng_math.cpp
      - deng/key_translation.c
      - deng/key_ev.c
      - deng/renderer.cpp
      - deng/window.cpp
      - deng/vulkan/vulkan_handler.c
      - deng/vulkan/vulkan_pipelines.cpp
      - deng/vulkan/vulkan_qm.cpp
      - deng/vulkan/vulkan_renderer.cpp
      - deng/vulkan/vulkan_resources.cpp
      - deng/vulkan/vulkan_sd.cpp
      linux: deng/x11_surface.c
      windows: deng/win32_surface.c

      # deng utilities sources
      - utils/font.cpp
      - utils/collision.cpp
      - utils/timer.cpp
      - utils/shapes.cpp
      - utils/grid_generator.cpp

      # dengui sources
      - dengui/vulkan/vulkan_update.cpp
      - dengui/dengui_child.cpp
      - dengui/dengui_events.cpp
      - dengui/dengui_window.cpp
      - dengui/map_editor_ui.cpp
      - dengui/ui_callbacks.cpp
        
      # common functionlity sources
      - common/common.c
      - common/hashmap.c

      # das sources
      - das/das_handler.c
      - das/data_loader.c
