import: 
  windows: 
    - modules/freetype2/build.yml
premake:
  cc: gcc
  cxx: g++
  cc_flags: 
    - Wall
    - m64
    - O3
  cxx_flags: 
    - Wall
    - m64 
    - std=c++11
    - O3
  include_path:
    linux:
      - "/usr/include/freetype2"
      - "/usr/include/freetype2/include"
    windows:
      - "modules/freetype2/include"
      - "modules/freetype2/include/freetype"
      - "C:/VulkanSDK/[VERSION]"
  src_dir: src/
  build_dir: build/
  project_name: deng

tasks: 
  dam:
    type: exec
    src:
      - das/dam.c
      - das/das_handler.c
      - das/data_loader.c
      - common/hashmap.c
      - common/common.c
  
  libdeng:
    type: dynamic_lib
    src: 
      - deng/camera.cpp
      - deng/renderer.cpp
      - deng/window.cpp
      - deng/rend_helpers.cpp
      - deng/deng_math.cpp
      - utils/font.cpp
      - utils/timer.cpp
      - utils/shapes.cpp
      - utils/grid_generator.cpp
      - dengui/dengui_events.cpp
      - dengui/dengui_window.cpp
      - dengui/map_editor_ui.cpp
      - common/common.c
      - common/hashmap.c
      - das/das_handler.c
      - das/data_loader.c
      - deng/key_translation.c
      - deng/key_vector.c
      - deng/vulkan_handler.c
      linux: deng/x11_surface.c
      windows: deng/win32_surface.c
