import: 
  windows: 
    - modules/freetype2/build.yml
premake:
  cc: gcc 
  cxx: g++ 
  cc_flags: 
    - Wall 
    - m64
    - g 
  cxx_flags: 
    - Wall 
    - m64 
    - std=c++11
    - g
  include_path:
    linux:
      - "/usr/include/freetype2"
      - "/usr/include/freetype2/include"
    windows:
      - "modules/freetype2/include"
      - "modules/freetype2/include/freetype"
      - "C:/VulkanSDK/[VERSION]"
  src_dir: src/
  build_dir: build/
  project_name: deng

tasks: 
  dam:
    type: exec
    src:
      - das/dam.c
      - das/das_handler.c
      - das/data_loader.c
      - common/common.c
  
  libdeng:
    type: dynamic_lib
    src: 
      - main/sandbox.cpp
      - core/camera.cpp
      - core/rend_helpers.cpp
      - core/renderer.cpp
      - core/window.cpp
      - maths/deng_math.cpp
      - maths/events.cpp
      - utilities/font.cpp
      - utilities/timer/timer.cpp
      - utilities/shapes.cpp
      - dengui/main/dengui_events.cpp
      - dengui/main/dengui_window.cpp
      - dengui/editor_uis/map_editor_ui.cpp
      - common/common.c
      - das/das_handler.c
      - das/data_loader.c
  
  libsurface:
    type: static_lib
    - surface/key_translation.c
    - surface/key_vector.c
    - surface/vulkan_handler.c
    linux: surface/x11_surface.c
    windows: surface/win32_surface.c
