import struct
import sys

struct_fmt = '=I'
struct_len = struct.calcsize(struct_fmt)
struct_unpack = struct.Struct(struct_fmt).unpack_from

if len(sys.argv) < 2:
    filename = input("Enter filename to read from: ")
else:
    filename = sys.argv[-1]

results = []

with open(filename, 'rb') as f:
    while True:
        data = f.read(struct_len)
        if not data:
            break
        s = struct_unpack(data)
        results.append(s)

print("/* Generated by Tools/spv2c.py */")
print()
print("const unsigned int spv[] = {", end='')

for i in range(len(results)):
    if i % 4 == 0:
        print('\n\t', end='')
    print("0x{:08x}, ".format(results[i][-1]), end='')

print("\n};")